In [1]:
import numpy as np

# 1.	Array Creation

In [4]:
arr_1D=np.arange(10,51)
print(arr_1D)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


In [7]:
arr_3x3=np.random.rand(3,3)
print(arr_3x3)

[[0.49415491 0.7358327  0.71280318]
 [0.24106488 0.38202799 0.97277075]
 [0.42752429 0.84291726 0.6270449 ]]


# 2.	Array Attributes

In [12]:
shape=arr_1D.shape
size=arr_1D.size
dtype=arr_1D.dtype
print(f'Shape:{shape},Size:{size},Dtype:{dtype}')

Shape:(41,),Size:41,Dtype:int64


# 3.	Basic Operations

In [14]:
arr_1D_plus5=arr_1D+5
print(arr_1D_plus5)

[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]


In [25]:
arr_2d_1 = np.random.rand(2, 2)
arr_2d_2 = np.random.rand(2, 2)
print('Arr1:',arr_2d_1)
print()
print('Arr2:',arr_2d_2)
print()
print('Mul:',arr_2d_1 * arr_2d_2)

Arr1: [[0.12834701 0.7675243 ]
 [0.63214721 0.43835402]]

Arr2: [[0.53314898 0.32256105]
 [0.42568579 0.54615024]]

Mul: [[0.06842808 0.24757344]
 [0.26909608 0.23940715]]


# 4.	Indexing and Slicing

In [28]:
arr_5x5=np.arange(1,26).reshape(5,5)
print(arr_5x5)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [30]:
arr_5x5[0,:]

array([1, 2, 3, 4, 5])

In [32]:
arr_5x5[:,-1]

array([ 5, 10, 15, 20, 25])

In [37]:
arr_5x5[:3,:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

# 5.	Aggregation

In [38]:
arr_10=np.random.randint(1,101,10)
print(arr_10)

[97 61 21 35 64 82  1 65  6 28]


In [43]:
max_value = np.max(arr_10)
min_value = np.min(arr_10)
mean_value = np.mean(arr_10)
std_value = np.std(arr_10)
print(f"Max: {max_value}, Min: {min_value}, Mean: {mean_value}, Std: {std_value}")

Max: 97, Min: 1, Mean: 46.0, Std: 30.82531427252608


# 6.	Reshaping

In [51]:
arr_1d=np.arange(1,13)
print(arr_1d)
arr_reshaped=arr.reshape(3,4)
print(arr_reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


# 7.	Broadcasting

In [56]:
arr_3x3_1s=np.ones((3,3))
print(arr_3x3_1s)
print()
broadcasted_arr=arr_3x3_1s+np.array([1,2,3])
print(broadcasted_arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


# 8.	Filtering

In [61]:
arr_random=np.random.randint(1,51,10)
print(arr_random)
filtered_arr=arr_random[arr_random%5==0]
print(filtered_arr)

[17  1  7 31 25 23 30 20 20  5]
[25 30 20 20  5]


# 9.	Matrix Multiplication

In [66]:
matrix_1 = np.random.rand(2, 2)
matrix_2 = np.random.rand(2, 2)
print(matrix_1)
print()
print(matrix_2)
print()
matrix_product=np.dot(matrix_1,matrix_2)
print(matrix_product)

[[0.31997571 0.79806653]
 [0.65982582 0.47442125]]

[[0.97907103 0.42445056]
 [0.11096188 0.68524482]]

[[0.40183391 0.68268483]
 [0.69865902 0.60515814]]


# 10.	Advanced Indexing

In [72]:
arr_4x4=np.random.randint(0,100, size=(4,4))
print(arr_4x4)
diag_ele=np.diagonal(arr_4x4)
print(diag_ele)

[[38 93 12 83]
 [ 6 54 22 10]
 [57 27  5 91]
 [24 47 16 52]]
[38 54  5 52]
